### ISSUE TITLE
Unable to connect to carelink

### ISSUE THREAD

**Issue by IoanaSara** [paul1956/CareLink#55] opened 2024-01-19 17:27 UTC
![image](https://github.com/paul1956/CareLink/assets/113257829/99d9e392-5159-4aa2-bcf2-55f20d16bbfd)
[CareLinkErrorReport(en-US)95.txt](https://github.com/paul1956/CareLink/files/13992312/CareLinkErrorReport.en-US.95.txt)

**Comment by paul1956** [comment] 2024-01-19 23:42
It is a Medtronic server issue; they are blocking access by changing the code sent to client.
The only solution is to let the program fill out the Medtronic Login screen and click the "I am not a Robot".  It you fill out any information manually it will always fail. If it does not automatically fill it in cancel and try again usually within 2 tries it will work.

This is a duplicate of #53

**Closed as completed by paul1956** 2024-01-19 23:42 UTC

**Comment by IoanaSara** [comment] 2024-01-21 04:18
I can only connect with version 4.0.0.4. With higher versions it doesn't work, the credentials are filled in automatically.
