### ISSUE TITLE
Login error - Sequence contains no elements

### ISSUE THREAD

**Issue by mattimart** [paul1956/CareLink#27] opened 2022-11-09 09:52 UTC
![image](https://user-images.githubusercontent.com/44461571/200776856-dec3e398-ff47-459f-995b-6d2c5482d0bf.png)

**Comment by nfontan** [comment] 2022-11-09 14:23
> ![image](https://user-images.githubusercontent.com/44461571/200776856-dec3e398-ff47-459f-995b-6d2c5482d0bf.png)

Please, attach the CareLinkErrorReport(en-US)xx.txt locate on c:\users\youruser\documents

**Comment by paul1956** [comment] 2022-11-10 01:33
@mattimart @nfontan I need the error report to look at this.

**Comment by paul1956** [comment] 2022-11-10 01:40
Just from looking at the error, it looks like server is returning no data for some of the fields and I don't guard against it. If I had error report, I could verify it.

**Comment by paul1956** [comment] 2022-11-10 05:09
[CareLink3.5.7.6x64.zip](https://github.com/paul1956/CareLink/files/9977489/CareLink3.5.7.6x64.zip)
Try this. these errors are caused by CareLink server or frontend down.

**Comment by paul1956** [comment] 2022-11-10 09:13
[CareLink3.5.7.6x64.zip](https://github.com/paul1956/CareLink/files/9979173/CareLink3.5.7.6x64.zip)

This fixes the issue, but it only happens when the CareLink server is flakey.

**Comment by paul1956** [comment] 2022-11-11 05:40
@mattimart @nfontan Fixed in CareLink3.5.7.7x64. Close if you agree.

**Closed as completed** 2022-11-11 08:00 UTC
