### ISSUE TITLE
Still not working...

### ISSUE THREAD

**Issue by Fishbaits** [paul1956/CareLink#14] opened 2022-08-08 07:42 UTC
Hi Paul

Thank you for all the effort you are and have been putting into this but there are still issues.
When I run the program, in about 1 minute I get error message of Unhandled exception.
![image](https://user-images.githubusercontent.com/37698892/183365509-72fc58b0-1580-4e70-a9e7-0fade5c9b0e6.png)
[CareLinkErrorReport(en-US).txt](https://github.com/paul1956/CareLink/files/9279811/CareLinkErrorReport.en-US.txt)

**Comment by paul1956** [comment] 2022-08-08 11:04
@Fishbaits it looks like bad data from CareLink that I am not dealing with. I will look at it late today. I assume if you reset it will fail immediately and probably clear itself in 24 hours. I will know more when I look at your error report which does reproduce the issue.

**Comment by paul1956** [comment] 2022-08-08 23:32
Please try this version CareLink3.5.0.4x64 and see if it fixes your issue.
It looks like it happens when your pump is disconnected from phone and because of the way I need to deal with international units instead of just ignoring it the app crashes.

**Comment by Fishbaits** [comment] 2022-08-10 08:25
Hi

The CareLink3.5.0.5x64 was the latest by now and this one works!
![image](https://user-images.githubusercontent.com/37698892/183852909-149daf49-3608-49dc-a2b8-ed7c0108e0f7.png)
The graph is there, everything is visible, great work!!
Thank you so very much!

**Comment by paul1956** [comment] 2022-08-10 12:10
@Fishbaits The graph looks odd to me I don't understand the green lines, can you send me the saved data file? There is a newer version that fixes the 154 on the display above. I will leave this open if you want to use it to send me the file or you can close it.

**Comment by Fishbaits** [comment] 2022-08-10 13:37
Hi
The latest works also ubt I do not see any difference really. Graph looks the same.
![image](https://user-images.githubusercontent.com/37698892/183912251-2dab9ca4-bb52-4058-ad5f-6431ffc6feb5.png)
I get a graph when I look at Running Active Insulin tab.
![image](https://user-images.githubusercontent.com/37698892/183913203-911e29ee-cb14-4de8-a3f1-82c855d6af88.png)

But what I personally miss the most is the speed of change. On big screen I cannot see it, on mini display it is there but numbers are in wrong unit again.
![image](https://user-images.githubusercontent.com/37698892/183914189-260b7a38-54b9-49a9-95b3-14c235a0aa48.png)

**Comment by Fishbaits** [comment] 2022-08-10 13:38
Where is this saved data file?
Everything in the Carelink folder has the same date and time, so I guess it is somewhere else?
Tried to do the Snapshot Save too but no clue where that went...

**Comment by paul1956** [comment] 2022-08-10 23:41
The working files are all saved in My Documents. I didn't write the mini display but will work on getting it fixe.

You can IM with me on Gitter as [paul1956](https://github.com/paul1956)

**Comment by paul1956** [comment] 2022-08-10 23:48
@Fishbaits 
These are what the graphs are supposed to look like
![image](https://user-images.githubusercontent.com/12789369/184041856-3e842892-1284-4366-9e48-ca30059bc593.png)
![image](https://user-images.githubusercontent.com/12789369/184041901-1331a927-ec60-487c-99a1-06d44b67854c.png)

**Comment by Fishbaits** [comment] 2022-08-11 07:21
Ok, these do look a bit different :)
One cause might also be, that I am running Win11.
[CareLinkLastDownload(et-EE).zip](https://github.com/paul1956/CareLink/files/9306898/CareLinkLastDownload.et-EE.zip)

**Comment by paul1956** [comment] 2022-08-11 08:04
Also on Windows 11. I fixed the 22 already. I will look into the zip tomorrow. This is what it should look like with European Data
![image](https://user-images.githubusercontent.com/12789369/184089749-4c77097d-c569-4f5c-8424-4cedca3b511a.png)
![image](https://user-images.githubusercontent.com/12789369/184090070-4aedb9d4-2a41-432c-a6c3-290e7e1efda2.png)

**Comment by paul1956** [comment] 2022-08-12 07:31
@Fishbaits The reason the graphs look like they do is there is very little data. If you look at the file (you can open in any text editor or Visual Studio will decode it), most of the values are NaN. I don't know why but the program is working correctly. Even the bgUnit data is missing. The red values in the image below are the green lines on your graph, I don't what what to do with this report. I am curious what the phone app looked like when this happened. The latest version I will post soon can deal with all the NaN values so it will not crash. You can then look at the raw data and maybe see what the issue might be.
![image](https://user-images.githubusercontent.com/12789369/184299351-6c23a16b-76f7-4610-928b-92745c585828.png)

**Comment by paul1956** [comment] 2022-08-12 20:08
@Fishbaits Try this it works on my system with your data.
[CareLink3.5.1.0x64.zip](https://github.com/paul1956/CareLink/files/9329571/CareLink3.5.1.0x64.zip)

**Comment by paul1956** [comment] 2022-08-12 20:54
@Fishbaits Issue finally found I was rounding small numbers with decimal points in some cultures
Here is the fixed version
![image](https://user-images.githubusercontent.com/12789369/184443254-c166dbbf-5171-4ce6-b0d5-df56e72e6740.png)
Please download from Release Branch. I will Close.

**Closed as completed by paul1956** 2022-08-12 20:54 UTC
