### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#21] opened 2022-09-26 09:20 UTC
i get a lot of build errors in the latest version.

![image](https://user-images.githubusercontent.com/4416348/192240486-a7304bc8-08a9-4bf0-93e0-23084c78d750.png)

**Comment by Krikke99** [comment] 2022-09-26 09:25
Also the latest release doesn't work anymore.

![image](https://user-images.githubusercontent.com/4416348/192241631-442c86f4-fce4-480e-850d-1fbafecd0f21.png)

**Comment by paul1956** [comment] 2022-09-27 05:16
@Krikke99 You need to Clone https://github.com/kirsan31/winforms-datavisualization its the new improved DataVisualization package but it is not available as a NewGet yet. Issue is fixed it was an initialization error caused by partial implementation of editor for the config file. It should be fixed in 3.5.6.6.

**Comment by Krikke99** [comment] 2022-09-28 11:55
@paul1956 build errors are gone, but both build and release now give this error

![image](https://user-images.githubusercontent.com/4416348/192772605-5b4f3c02-4cae-4ce6-931c-3d65ae7f8feb.png)

**Comment by paul1956** [comment] 2022-09-29 01:12
@Krikke99 Try deleting Carelink.csv in myDocuments I think it is corrupt. I put in some fixes for that in a version I am working on but not ready to release. Otherwise, can you set a break on Link 164 and tell me what past of the line is Nothing.

**Closed as completed** 2022-09-30 07:28 UTC

**Comment by Krikke99** [comment] 2022-09-30 07:30
After deleting the file everything works again.
